-- アカウントテーブル
INSERT INTO TACCOUNT(TACCOUNT_ID, MAIL_ADDRESS, PASSWORD, IS_DELETED, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT) VALUES(1, 'guest@sblib.com', 'pass', '0', 'admin', CURRENT_TIMESTAMP(), 'admin', CURRENT_TIMESTAMP());
INSERT INTO TACCOUNT(TACCOUNT_ID, MAIL_ADDRESS, PASSWORD, IS_DELETED, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT) VALUES(2, 'gnruser@sblib.com', 'pass', '0', 'admin', CURRENT_TIMESTAMP(), 'admin', CURRENT_TIMESTAMP());
INSERT INTO TACCOUNT(TACCOUNT_ID, MAIL_ADDRESS, PASSWORD, IS_DELETED, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT) VALUES(3, 'cmpuser@sblib.com', 'pass', '0', 'admin', CURRENT_TIMESTAMP(), 'admin', CURRENT_TIMESTAMP());
INSERT INTO TACCOUNT(TACCOUNT_ID, MAIL_ADDRESS, PASSWORD, IS_DELETED, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT) VALUES(4, 'master@sblib.com', 'pass', '0', 'admin', CURRENT_TIMESTAMP(), 'admin', CURRENT_TIMESTAMP());
INSERT INTO TACCOUNT(TACCOUNT_ID, MAIL_ADDRESS, PASSWORD, IS_DELETED, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT) VALUES(5, 'grandmaster@sblib.com', 'pass', '0', 'admin', CURRENT_TIMESTAMP(), 'admin', CURRENT_TIMESTAMP());
